name: Docker Build & Release

on:
  # build and release a new docker image and helm package for specific tags.
  release:
    types: [prereleased, released]

jobs:
  build:
    # Github action path and version
    uses: biceventures/common_docker_actions/.github/workflows/docker_release.yml@stable
    # Require inputs of this workflow
    with:
      # App name or service name / use repository name by default.
      project_name: ${{ github.event.repository.name }}
      values_file_path: ./helm/chart/app/values.yaml # replace app with the app folder name
      chart_path: ./helm/chart/
      # Aditional inputs handled by this action
      # dockerfile_path: Path to the Dockerfile. Default is Dockerfile. (default: Dockerfile)
    secrets: inherit # inherit all secrets to the action
    # secrets handled by this action:
    # - CLEVER_DOCKER_REGISTRY: Google artifact docker registry (required)
    # - CLEVER_HELM_REGISTRY: Google artifact helm registry (required)
    # - APP_KSA: App kubernetes service account (optional)
    # - APP_GSA: App Google Service Account (optional)
    # - GOOGLE_PROJECT_ID: Google project ID where this app will be deployed. (optional)
    # - BUILD_ARGS: Comma separated list of extra build-args for docker (optional)