name: Docker Build & Security Scan

on:
  # build and test in PRs
  pull_request:
    # paths: If at least one path matches a pattern in the paths filter, the workflow runs.
    # also paths-ignore can be used: When all the path names match patterns in paths-ignore,
    # the workflow will not run. If any path names do not match patterns in paths-ignore, even
    # if some path names match the patterns, the workflow will run.
    # You can not use paths and paths-ignore to filter the same event in a single workflow.
    # If you want to both include and exclude path patterns for a single event, use the paths 
    # filter along with the ! character to indicate which paths should be excluded.
    paths: 
     - 'Dockerfile'
     - 'src/**'
     - '!src/docs/**' 
    
jobs:
  build_and_scan:
    # Github action path and version
    uses: clever-cl/common_docker_actions/.github/workflows/docker_scan.yml@stable
    # Require inputs for this workflow
    with:
      # App name or service name / use repository name by default.
      project_name: ${{ github.event.repository.name }}
      # Aditional inputs handled by this action
      # dockerfile_path: Path to the Dockerfile. Default is Dockerfile. (default: Dockerfile)
    secrets: inherit # inherit all secrets to the action
    # secrets handled by this action:
    # - CLEVER_DOCKER_REGISTRY: Google artifact registry (required)
    # - BUILD_ARGS: Comma separated list of extra build-args for docker (not required)
