name: Docker Security Scan

on:
  # build and test in PRs
  pull_request:
    paths:
     - Dockerfile
     - src/**

jobs:
  build_docker:
    # Github action path and version
    uses: biceventures/common_docker_actions/.github/workflows/docker_scan.yml@stable
    # Require inputs for this workflow
    with:
      # App name or service name / use repository name by default.
      project_name: ${{ github.event.repository.name }}